name: Docker Build & Push Action

on:
  workflow_dispatch:
  push:
      branches:
        - main

jobs: 
  build-rtems-6:    
    
    name: Build and Push qemu-rtems-6
    runs-on: ubuntu-latest
    
    steps:                     
      - name: Checkout code
        uses: actions/checkout@v2        

      - name: Build and Push 
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: qemu-rtems-6
          dockerfile: rtems-6/Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest

  build-rtems-5:    
    
    name: Build and Push qemu-rtems-5
    runs-on: ubuntu-latest
    
    steps:                     
      - name: Checkout code
        uses: actions/checkout@v2        
          
      - name: Build Docker image
        id: build
        run: |
          docker build -f rtems-5/Dockerfile -t ghcr.io/arielswalker/qemu-rtems-5:latest .

      - name: Retrieve build logs
        if: failure()
        run: |
          docker cp $(docker ps -q -f "ancestor=ghcr.io/arielswalker/qemu-rtems-5:latest"):/logs/sb-set-builder.log ./sb-set-builder.log || true

      - name: Upload build logs as artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: ./sb-set-builder.log
          
  build-rtems-4-11:      
      
      name: Build and Push qemu-rtems-4-11
      runs-on: ubuntu-latest
      
      steps:                     
        - name: Checkout code
          uses: actions/checkout@v2        

        - name: Build and Push 
          uses: mr-smithers-excellent/docker-build-push@v5
          with:
            image: qemu-rtems-4-11
            dockerfile: rtems-4.11/Dockerfile
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            tags: latest
